### PR TITLE
2 to 3

### PR DESCRIPTION
**Pull request by cbroschinski**
Here's the new py3 variant of both the enrichment script and the toolkit library. Unfortunately I wasn't able to test if it's called and executed correctly - process_apc_files expects a file which is not part of the repo ("File list not found in: ../../test/test_file_list.txt")

### CODE REVIEW

**Comment by camillalindelow** [comment]
Great thanks Christoph!

**Comment by camillalindelow** [comment]
Christoph,
Our script, process_apc_files.py, depends on the attribute UnicodeReader, that is no longer available in your 3-script, see error message below. Could you please point me to the new solution?

AttributeError: module 'python.openapc_toolkit' has no attribute 'UnicodeReader'

Thanks a lot!
Camilla

**Comment by cbroschinski** [comment]
Hi Camilla,

UnicodeReader was a workaround I had implemented because the csv module
in python2 could not handle non-ASCII files properly. That's no longer
the case in python3 where everything's represented as a uniode string by
default. You should be able to replace instances of UnicodeReader by
either a reader or DictReader from the python3 csv module
(https://docs.python.org/3.1/library/csv.html#module-contents). The
toolkit file should contain some example code on how to make use of a
DictReader object.

Best,

Christoph

**Comment by camillalindelow** [comment]
Thanks Christoph! We'll try that out.

**Pull request merged**
